"""add analytics snapshots

Revision ID: fa5970e0cdd6
Revises: 52864d5b5cf3
Create Date: 2026-09-05 01:11:22.436000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa5970e0cdd6'
down_revision: Union[str, Sequence[str], None] = '52864d5b5cf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.Column('jobs_total', sa.Integer(), nullable=True),
    sa.Column('jobs_done', sa.Integer(), nullable=True),
    sa.Column('sla_compliance_pct', sa.Float(), nullable=True),
    sa.Column('avg_response_min', sa.Float(), nullable=True),
    sa.Column('captures_total', sa.Integer(), nullable=True),
    sa.Column('captures_verified', sa.Integer(), nullable=True),
    sa.Column('captures_flagged_open', sa.Integer(), nullable=True),
    sa.Column('captures_resolved', sa.Integer(), nullable=True),
    sa.Column('auto_verify_pct', sa.Float(), nullable=True),
    sa.Column('jobs_by_type', sa.JSON(), nullable=True),
    sa.Column('jobs_by_industry', sa.JSON(), nullable=True),
    sa.Column('technician_leaderboard', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analytics_snapshots')
    # ### end Alembic commands ###
